import funan3 from "../images/funan_3.jpg";
const thoughts = [
  {
    id: 1,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 2,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 3,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 4,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 5,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 6,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 1,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 2,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 3,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 4,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 5,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 6,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 1,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 2,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 3,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 4,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 5,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 6,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 1,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 2,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 3,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 4,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 5,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
  {
    id: 6,
    link: "/reference",
    image: funan3,
    title: "funan centre",
    subtitle: "funan centre the new place",
  },
];

export default thoughts;
